package com.example.thinkableproject;

public class Job_items {
    public static final String[] items = new String[]{"Able Seamen", "Account Collector", "Able Seamen",
            "Account Collector",
            "Accounting Specialist",
            "Adjustment Clerk",
            "Administrative Assistant",
            "Administrative Law Judge",
            "Administrative Service Manager",
            "Admiralty Lawyer",
            "Adult Literacy and Remedial Education Teachers",
            "Advertising Account Executive",
            "Advertising Agency Coordinator",
            "Aeronautical & Aerospace Engineer",
            "Aerospace Engineering Technician",
            "Agricultural Crop Farm Manager",
            "Agricultural Engineer",
            "Agricultural Equipment Operator",
            "Agricultural Inspector",
            "Agricultural Product Sorter",
            "Agricultural Sciences Professor",
            "Agricultural Technician",
            "Air Crew Member",
            "Air Crew Officer",
            "Air Traffic Controller",
            "Aircraft Assembler",
            "Aircraft Body and Bonded Structure Repairer",
            "Aircraft Cargo Handling Supervisor",
            "Aircraft Examiner",
            "Aircraft Launch and Recovery Officer",
            "Aircraft Launch and Recovery Specialist",
            "Aircraft Mechanic",
            "Airfield Operations Specialist",
            "Airline Flight Attendant",
            "Airline Flight Control Administrator",
            "Airline Flight Operations Administrator",
            "Airline Flight Reservations Administrator",
            "Airport Administrator",
            "Airport Design Engineer",
            "Alcohol & Drug Abuse Assistance Coordinator",
            "Alumni Relations Coordinator",
            "Ambulance Drivers",
            "Amusement Park & Recreation Attendants",
            "Anesthesiologist (MD)",
            "Animal Breeder",
            "Animal Control Worker",
            "Animal Husbandry Worker Supervisor",
            "Animal Keepers and Groomers",
            "Animal Kennel Supervisor",
            "Animal Scientist",
            "Animal Trainer",
            "Animation Cartoonist",
            "Answering Service Operator",
            "Anthropology and Archeology Professor",
            "Anti-Terrorism Intelligence Agent",
            "Appeals Referee",
            "Aquaculturist (Fish Farmer)",
            "Aquarium Curator",
            "Architecture Professor",
            "Area, Ethnic, and Cultural Studies Professor",
            "Armored Assault Vehicle Crew Member",
            "Armored Assault Vehicle Officer",
            "Art Appraiser",
            "Art Director",
            "Art Restorer",
            "Art Therapist",
            "Art, Drama, and Music Professor",
            "Artillery and Missile Crew Member",
            "Artillery and Missile Officer",
            "Artists Agent (Manager)",
            "Athletes' Business Manager",
            "Athletic Coach",
            "Athletic Director",
            "Athletic Trainer",
            "ATM Machine Servicer",
            "Atmospheric and Space Scientist",
            "Audio-Visual Collections Specialist",
            "Audiovisual Production Specialist",
            "Automobile Mechanic",
            "Automotive Body Repairer",
            "Automotive Engineer",
            "Automotive Glass Installer",
            "Avionics Technician",
            "Baggage Porters and Bellhops",
            "Baker (Commercial)",
            "Ballistics Expert",
            "Bank and Branch Managers",
            "Bank Examiner",
            "Bank Teller",
            "Benefits Manager",
            "Bicycle Mechanic",
            "Billing Specialist",
            "Bindery Machine Set-Up Operators",
            "Bindery Machine Tender",
            "Biological Technician",
            "Biology Professor",
            "Biomedical Engineer",
            "Biomedical Equipment Technician",
            "Boat Builder",
            "Book Editor",
            "Border Patrol Agent",
            "Brattice Builder",
            "Bridge and Lock Tenders",
            "Broadcast News Analyst",
            "Cardiologist (MD)",
            "Cardiopulmonary Technologist",
            "Dry Wall Installer",
            "Economics Professor",
            "Editorial Writer, Newspapers & Magazines",
            "Education and Training Administrator",
            "Education Professor",
            "Educational Administrator",
            "Educational Psychologist",
            "Educational Resource Coordinator",
            "Educational Therapist",
            "Excavating Supervisor",
            "Executive Secretary",
            "Exercise Physiologist",
            "Exhibit Artist",
            "Exhibit Designer",
            "Experimental Psychologist",
            "Explosives Worker",
            "Export Agent",
            "Fashion Artist",
            "Fashion Coordinator",
            "Fashion Designer",
            "Fashion Model",
            "Financial Examiner",
            "Financial Planner",
            "Numerical Tool Programmer",
            "Nurse Practitioner",
            "Nurse's Aide",
            "Nursery Workers",
            "Nursing Professor",
            "Obstetrician (MD)",
            "Office Clerk",
            "Orthodontist (MD)",
            "Pathologist (MD)",

            "Pediatrician (MD)",


            "Physical Education Instructor",
            "Physical Therapist",
            "Physics Professor",
            "Pilot (Commercial Airlines)",

            "Police Officer",

            "Postmasters and Mail Superintendents",

            "Preschool Teacher",
            "Pressing Machine Operator",
            "Pressure Vessel Inspectors",
            "Printing/Graphic Arts Reproduction Technician",
            "Printmaker (Artist)", "Physician(MD)",

            "Psychiatrist (MD)",
            "Psychology Professor",
            "Public Health Service Officer",
            "Public Relations Manager",

            "Purchasing Manager",

            "Quarry Worker",
            "Radar and Sonar Technicians",
            "Radiation Protection Engineer",
            "Radiation Therapists",
            "Radio & TV Announcer",
            "Radio & TV News Commentator",
            "Radio & TV Newscaster",
            "Radio & TV Producer",
            "Radio Operators",
            "Radiologic Technicians",
            "Radiologic Technologist",
            "Radiologist (MD)",
            "Rail Yard Engineers",
            "Railroad Conductors and Yardmasters",
            "Railroad Engineer",
            "Railroad Inspector",
            "Screen Writer",
            "Script Editor",
            "Securities Broker",
            "Security and Fire Alarm Systems Installers",
            "Security Guard",
            "Social Worker",
            "Sociology Professor",
            "Soil Conservation Technician",
            "Soil Conservationist",
            "Soil Engineer",
            "Surgeons (MD)",
            "Surgical Technician/Technologist",
            "Survey Researchers",
            "Tax Accountant",
            "Tax Auditor",
            "Tax Collector",
            "Tax Examiner",
            "Tax Lawyer",
            "Tax Preparer",
            "Taxi Drivers and Chauffeurs",
            "Teacher",
            "Textile Designer",

            "Veterinarian (VMD)",
            "Veterinarian Technician",
            "Veterinary Assistant",
            "Video Engineer",

            "Web Art Director",
            "Writer /Author",
            "Zoo Veterinarian",
            "Zoologist",
            "Software Engineer", "Electrical Engineer", "Chemical Engineer"};
}
